services:
  - type: web
    name: realestate-ai-agent
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENTS
        sync: false
