services:
  - type: web
    name: realestate-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "import os; open('__init__.py', 'a').close()"
    startCommand: |
      export PYTHONPATH=/opt/render/project/src:$PYTHONPATH
      gunicorn app:app
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENTS
        sync: false
