services:
  - type: web
    name: realestate-ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENTS
        sync: false
